
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 13;
  public static final int PREFIX = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int IF = 7;
  public static final int RBRACKET = 6;
  public static final int ELSE = 8;
  public static final int COMMA = 9;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int SUFFIX = 12;
  public static final int LBRACKET = 5;
  public static final int LPAREN = 3;
  public static final int NAME = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "IF",
  "ELSE",
  "COMMA",
  "NAME",
  "PREFIX",
  "SUFFIX",
  "STRING_LITERAL"
  };
}

